### ISSUE TITLE
[分布式部署] 如何编译分布式环境下执行的可执行程序？

### ISSUE THREAD

**Issue by diffm** [ComputationalAdvertising/DiMLSys#4]
* 涉及到的问题主要有：
* 1. dmlc-core分布式编译成libdmlc*.a，包括hdfs等依赖;
* 2. 项目可执行程序 包括 依赖文件，需要用cmake完成make过程。

**Comment by ComputationalAdvertising** [comment]
libdmlc.a分布式编译同样可以在local下运行，已经通过xgboost得到验证；
libdmlc.a分布式本身应该没有问题，问题还是出现在编译配置，需要结合xgboost的CMakeLists进一步排查 ...

**Comment by ComputationalAdvertising** [comment]
distr_m已经编译成功，可以运行代码。问题还是集中在CMakeLists编译配置问题。高清楚cmake与makefile的转换关系。熟悉cmake语法 ....

**Comment by ComputationalAdvertising** [comment]
在distr_m上修改MakeFile文件的依赖，看错误是否重现。修改LIBS：
修改前：```LIBS += -lpthread -lrabit -ldmlc -lhdfs -lhadoop -ljvm -lrt -ldl```
修改后：```LIBS += -lpthread -lrabit -ldmlc -lhadoop -ljvm -lrt -ldl```
去除-lhdfs之后发现make报错：
```
./third_party/root/lib/libdmlc.a(hdfs_filesys.o): In function `dmlc::io::HDFSFileSystem::HDFSFileSystem(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
hdfs_filesys.cc:(.text+0xb1): undefined reference to `hdfsConnect'
./third_party/root/lib/libdmlc.a(hdfs_filesys.o): In function `dmlc::io::HDFSFileSystem::GetPathInfo(dmlc::io::URI const&)':
hdfs_filesys.cc:(.text+0xcd0): undefined reference to `hdfsGetPathInfo'
hdfs_filesys.cc:(.text+0x143a): undefined reference to `hdfsFreeFileInfo'
./third_party/root/lib/libdmlc.a(hdfs_filesys.o): In function `dmlc::io::HDFSFileSystem::ResetNamenode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
hdfs_filesys.cc:(.text+0x206f): undefined reference to `hdfsDisconnect'
hdfs_filesys.cc:(.text+0x2523): undefined reference to `hdfsConnect'
```
初步猜测原因是本项目CMakeLists中缺少库依赖所致，更新cmake继续看编译结果...

**Comment by ComputationalAdvertising** [comment]
问题已经解决。主要原因是admm_learner的依赖中涉及到dmlc, 而dmlc的分布式yarn编译又依赖hdfs、Hadoop等。在编写src/CMakeLists.txt时没有添加hdfs、hadoop等库依赖，只是src/原文件找不到hdfsConnect等函数。
set(admm_LINKER_LIBS "")
list(APPEND admm_LINKER_LIBS ${static_lib_name})
list(APPEND admm_LINKER_LIBS pthread)
list(APPEND admm_LINKER_LIBS dmlc)
list(APPEND admm_LINKER_LIBS rabit)
修改前：target_link_libraries(${exec_name} ${admm_LINKER_LIBS})
修改后：target_link_libraries(${exec_name} ${admm_LINKER_LIBS} hdfs hadoop jvm rt dl)
总结：**使用dmlc-core依赖时，一定要添加hdfs、hadoop等动态依赖库**

排查构建问题 4步走：
1. 定位问题。是include找不到，还是lib找不到，亦或者CXXFLAGS中缺失编译参数
2. 如果是include找不到，在```include_directories```中添加；如果是lib不存在，则下载；
3. 如果是未链接到库的目录需要使用```link_libraries()```添加进来；并且在使用处对应的CMakeLists.txt中通过```target_link_libraries()```链接进来；
4. 缺失编译参数，如```openmp, pthread```等属于这一类；
